<a href="https://colab.research.google.com/github/AliEmreKeskin/pytorch-tuts/blob/master/01_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

x=torch.Tensor([5,3])
y=torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [2]:
x=torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [3]:
x.shape

torch.Size([2, 5])

In [4]:
y=torch.rand([2,5])
y

tensor([[0.4391, 0.0722, 0.5557, 0.5398, 0.1963],
        [0.3097, 0.9020, 0.0210, 0.9602, 0.1049]])

In [5]:
y=y.view([1,10])
y

tensor([[0.4391, 0.0722, 0.5557, 0.5398, 0.1963, 0.3097, 0.9020, 0.0210, 0.9602,
         0.1049]])